version: '2'
services:
    qualopt-app:
        image: qualopt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://qualopt-mysql:3306/qualopt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    qualopt-mysql:
        extends:
            file: mysql.yml
            service: qualopt-mysql
